// Generated by dojo-bindgen on Mon, 2 Dec 2024 16:54:58 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `dojo_starter::models::SkillsValue` struct
[Serializable]
public struct SkillsValue {
    public bool has_water;
    public bool has_fire;
    public bool has_electric;
}


namespace dojo_starter {
    // Model definition for `dojo_starter::models::Skills` model
    public class Skills : ModelInstance {
        [ModelField("player")]
        public FieldElement player;

        [ModelField("has_water")]
        public bool has_water;

        [ModelField("has_fire")]
        public bool has_fire;

        [ModelField("has_electric")]
        public bool has_electric;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        