// Generated by dojo-bindgen on Mon, 2 Dec 2024 16:54:58 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `dojo_starter::models::MovesValue` struct
[Serializable]
public struct MovesValue
{
    public ulong remaining:100;
    public ulong steps_moved;
    public Direction last_direction;
    public bool can_move;
}


namespace dojo_starter
{
    // Model definition for `dojo_starter::models::Moves` model
    public class Moves : ModelInstance
    {
        [ModelField("player")]
        public FieldElement player;

        [ModelField("remaining")]
        public ulong remaining;

        [ModelField("steps_moved")]
        public ulong steps_moved;

        [ModelField("last_direction")]
        public Direction last_direction;

        [ModelField("can_move")]
        public bool can_move;

        // Start is called before the first frame update
        void Start()
        {
        }

        // Update is called once per frame
        void Update()
        {
        }
    }
}

