// Generated by dojo-bindgen on Mon, 2 Dec 2024 16:54:58 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `dojo_starter::models::PointsValue` struct
[Serializable]
public struct PointsValue {
    public ulong total_points;
}


namespace dojo_starter {
    // Model definition for `dojo_starter::models::Points` model
    public class Points : ModelInstance {
        [ModelField("player")]
        public FieldElement player;

        [ModelField("total_points")]
        public ulong total_points;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        